### ISSUE TITLE
With Winston1.2.12 ImportHypoinverse gets wrong hemisphere

### ISSUE THREAD

**Issue by stefanisti** [usgs/winston#80] opened 2019-06-03 03:24 UTC
Using the Memphis test again (http://www.earthwormcentral.org/distribution/memphis_test.zip) I do:
C:\earthworm\Winston1.2.12>java -cp \earthworm\Winston1.2.12\lib\winston.jar gov.usgs.winston.in.metadata.ImportHypoinverse %EW_PARAMS%\memphis.hinv

But the stations on the Swarm map instead of appearing in Tennessee appear somewhere around Mongolia. 

Here are a couple lines of the hinv file:
MLNT  NM ZEGZ  35 20.0400  89  49.800   100.0   A 0.00  0.00  0.00  0.00 1  0.00
MLNT  NM NEGN  35 20.0400  89  49.800   100.0   A 0.00  0.00  0.00  0.00 1  0.00
MLNT  NM EEGE  35 20.0400  89  49.800   100.0   A 0.00  0.00  0.00  0.00 1  0.00
RALT  NM ZEGZ  35 12.3600  89  56.460   100.0   R 0.00  0.00  0.00  0.00 1  0.00
RALT  NM NEGN  35 12.3600  89  56.460   100.0   R 0.00  0.00  0.00  0.00 1  0.00
RALT  NM EEGE  35 12.3600  89  56.460   100.0   R 0.00  0.00  0.00  0.00 1  0.00

(Sorry if this is fixed in 1.3, I'm not using it because of the issues I'm having with Swarm and 1.3.)

**Comment by tparker-usgs** [comment] 2019-07-24 17:51
Duplicate of #65

**Closed as completed by tparker-usgs** 2019-07-24 17:51 UTC
